[project]
name = "math2b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "polars>=1.27.1",
    "sympy>=1.14.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]
